### ISSUE TITLE
Some help for extension usage needed

### ISSUE THREAD

**Issue by jantma2** [xperseguers/t3ext-push_notification#1]
Hello,

I've managed to install this extension to my TYPO3 V12.
No error messages occur, but I don't really understand the idea of how this extension is going to work.

Some help would be appreciated.
So what did I need to do after the setup? Where could I use the APIs?
Thanks in advance for your support.

Best Regards.

**Comment by xperseguers** [comment]
Did you read the README? This is an extension targeted at developers, so you may use it in your own extension. The README should explain "everything" you need to know.

**Comment by xperseguers** [comment]
Please note however that I stopped using it myself and switched instead to:

- https://packagist.org/packages/edamov/pushok
- https://packagist.org/packages/edwinhoksberg/php-fcm

as it turned out they were properly maintained and working just great.
